version: '3.7'

services:
  web:
    build: .
    ports:
      - 8007:8765
    environment:
      - PORT=8765
      - DEBUG=1
      - DATABASE_URL=postgres://django_transfer:django_transfer@db:5432/django_transfer_dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_transfer
      - POSTGRES_PASSWORD=django_transfer
      - POSTGRES_DB=django_transfer_dev

volumes:
  postgres_data: